version: 2.1

commands:
  influxdb-onboarding:
    parameters:
      script-name:
        type: string
        default: "influxdb-onboarding"
    steps:
      - run:
          name: "Post onBoarding request to InfluxDB 2"
          command: ./scripts/<< parameters.script-name >>.sh
  build-generator:
    steps:
      - run: mvn -f openapi-generator/pom.xml clean install -DskipTests
  download-oss-swagger:
    steps:
      - run: curl https://raw.githubusercontent.com/influxdata/openapi/master/contracts/oss.yml --output ./oss.yml
  clone-client:
    parameters:
      client:
        type: string
      branch:
        type: string
    steps:
      - run:
          command: |
            mkdir -p ./build
            git clone --single-branch --branch << parameters.branch >> https://github.com/influxdata/<< parameters.client >> ./build/<< parameters.client >>

jobs:
  generate-client:
    docker:
      - image: "circleci/openjdk:8-stretch"
    parameters:
      client:
        type: string
      branch:
        type: string
        default: "master"
    steps:
      - checkout
      - restore_cache:
          name: Restoring Maven Cache
          keys:
            - &cache-key maven-cache_v1-{{ checksum "openapi-generator/pom.xml" }}
            - maven-cache_v1
      - build-generator
      - download-oss-swagger
      - clone-client:
          client: influxdb-client-<< parameters.client >>
          branch: << parameters.branch >>
      - run:
          name: "Generate << parameters.client >> client"
          command: |
            ./generate-<< parameters.client >>.sh
      - persist_to_workspace:
          root: build
          paths:
            - ./influxdb-client-<< parameters.client >>
      - save_cache:
          name: Saving Maven Cache
          key: *cache-key
          paths:
            - ~/.m2
  check-generated-python:
    docker:
      - image: "circleci/python:3.6-buster"
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: "influxdb:latest"
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :8086
    steps:
      - checkout
      - influxdb-onboarding
      - attach_workspace:
          at: ./build
      - restore_cache:
          name: Restoring Pip Cache
          keys:
            - &cache-key pip-cache-v1-{{ checksum "build/influxdb-client-python/setup.py" }}
            - pip-cache-v1
      - run:
          name: "Check Generated Client"
          command: |
            cd ./build/influxdb-client-python
            pip install -e . --user
            pip install -e .\[extra\] --user
            pip install -e .\[test\] --user
            mkdir test-reports || true
            pytest tests --junitxml=test-reports/junit.xml
      - store_test_results:
          path: ./build/influxdb-client-python/test-reports
      - save_cache:
          name: Saving Pip Cache
          key: *cache-key
          paths:
            - ".venv"
            - "~/.cache/pip"
  check-generated-csharp:
    docker:
      - image: "mcr.microsoft.com/dotnet/core/sdk:3.1"
        environment:
          NET_TARGET_VERSION: netstandard2.1
      - image: "influxdb:latest"
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :9999
      - image: "influxdb:latest"
        name: influxdb_v2_onboarding
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :9999
      - image: influxdb:1.8-alpine
        environment:
          INFLUXDB_HTTP_FLUX_ENABLED: true
    environment:
      INFLUXDB_2_ONBOARDING_IP: influxdb_v2_onboarding
      INFLUXDB_2_ONBOARDING_PORT: 9999
    steps:
      - checkout
      - influxdb-onboarding:
          script-name: "influxdb-onboarding-v1v2"
      - attach_workspace:
          at: ./build
      - run:
          name: "Check Generated Client"
          command: |
            cd ./build/influxdb-client-csharp
            ./Scripts/ci-test.sh false
            mkdir test-results
            mkdir test-results/client-legacy
            cp -r Client.Legacy.Test/TestResults/*.xml test-results/client-legacy || true
            mkdir test-results/client-linq
            cp -r Client.Linq.Test/TestResults/*.xml test-results/client-linq || true
            mkdir test-results/client
            cp -r Client.Test/TestResults/*.xml test-results/client || true
            mkdir test-results/client-core
            cp -r Client.Core.Test/TestResults/*.xml test-results/client-core || true
      - store_test_results:
          path: ./build/influxdb-client-csharp/test-results

workflows:
  version: 2
  build:
    jobs:
      - generate-client:
          name: generate-python
          client: python
      - generate-client:
          name: generate-csharp
          client: csharp
      - check-generated-python:
          requires:
            - generate-python
      - check-generated-csharp:
          requires:
            - generate-csharp

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-client:
          name: generate-python
          client: python
      - generate-client:
          name: generate-csharp
          client: csharp
      - check-generated-python:
          requires:
            - generate-python
      - check-generated-csharp:
          requires:
            - generate-csharp
